### ISSUE TITLE
Compatibility with stackview 0.9.0?

### ISSUE THREAD

**Issue by tcompa** [haesleinhuepf/napari-workflows#47]
Hi there,
As of stackview 0.9.0 (which notably includes https://github.com/haesleinhuepf/stackview/pull/68), we start observing some errors when using `napari-workflows` in https://github.com/fractal-analytics-platform/fractal-tasks-core (see relevant issue: https://github.com/fractal-analytics-platform/fractal-napari-workflows/issues/6).

I don't have a minimal working example yet, but the specific error we hit is when calling `numpy.unique` on an array which is a napari-workflows output (that is, it comes from `napari_workflow`'s `Workflow.get(...)`).

The output object has the following properties
```
fractal_tasks_core/tasks/napari_workflows_wrapper.py:550 napari_workflows_wrapper
    mask: (
        StackViewNDArray([[[ 0,  0,  0, ...,  0,  0,  0],
                           [ 0,  0,  0, ...,  0,  0,  0],
                           [ 0,  0,  0, ...,  0,  0,  0],
                           ...,
                           [ 0,  0,  0, ..., 60, 60, 60],
                           [ 0,  0,  0, ..., 60, 60, 60],
                           [ 0,  0,  0, ..., 60, 60, 60]],
                          [[ 0,  0,  0, ...,  0,  0,  0],
                           [ 0,  0,  0, ...,  0,  0,  0],
                           [ 0,  0,  0, ...,  0,  0,  0],
                           ...,
                           [ 0,  0,  0, ..., 60, 60, 60],
                           [ 0,  0,  0, ..., 60, 60, 60],
                           [ 0,  0,  0, ..., 60, 60, 60]]], dtype=int32)
    ) (StackViewNDArray) len=2

fractal_tasks_core/tasks/napari_workflows_wrapper.py:551 napari_workflows_wrapper
    mask.shape: (
        2,
        540,
        640,
    ) (tuple) len=3
```
where the shape look correct.

When we then pass it to `numpy.unique`, this leads to an internal error
```
ValueError: could not broadcast input array from shape (539,640) into shape (345599,)
```
where it's unclear to me what these shapes represent.

---

Would you mind clarifying what was the reason behind https://github.com/haesleinhuepf/stackview/pull/68, so that we can review whether this is a bug on our side? Thank you!

**Comment by haesleinhuepf** [comment]
Thanks for reporting this @tcompa ! I also don't understand the issue yet, but I suspect that this is the relevant change:
https://github.com/haesleinhuepf/stackview/commit/afe4fd24baa492397fb9a7ab8c5f71cdd2e08672

CC @jo-mueller

**Comment by tcompa** [comment]
> but I suspect that this is the relevant change: https://github.com/haesleinhuepf/stackview/commit/afe4fd24baa492397fb9a7ab8c5f71cdd2e08672

Yes, I can confirm this is the case.
I tried using 0.9.0 but reverting that specific change, and the error was not there any more (reported in  https://github.com/fractal-analytics-platform/fractal-napari-workflows/issues/6#issuecomment-2320471319).

**Comment by haesleinhuepf** [comment]
Ok, this should be fixed in stackview 0.9.1 - even though I'm afraid there may be more follow-up changes necessary.

The new version is available on pypi. Conda-forge may follow in 12-24h. @tcompa if you could test it again next week it would be awesome. Thanks for reporting the bug!

**Comment by tcompa** [comment]
> Ok, this should be fixed in stackview 0.9.1

I confirm this fixes a specific test that was failing with 0.9.0:

```bash
# Setup appropriate environment
git clone https://github.com/fractal-analytics-platform/fractal-tasks-core.git
cd fractal-tasks-core
python -m venv venv
source venv/bin/activate
python -m pip install -e .[fractal-tasks]
python -m pip install pytest devtools jsonschema requests wget pooch

# Run tests with stackview 0.8.2
python -m pip show stackview
# 0.8.2
python -m pytest tests/tasks/test_workflows_napari_workflows.py::test_napari_workflow -v
# PASSED

# Run tests with stackview 0.9.0
python -m pip install stackview==0.9.0
python -m pytest tests/tasks/test_workflows_napari_workflows.py::test_napari_workflow -v
# FAILED

# Run tests with stackview 0.9.1
python -m pip install stackview==0.9.1
python -m pytest tests/tasks/test_workflows_napari_workflows.py::test_napari_workflow -v
# PASSED
```

**Comment by tcompa** [comment]
But at least one other test still fails, with 0.9.1:
```
FAILED tests/tasks/test_workflows_napari_workflows.py::test_expected_dimensions[2-2-True-True] - IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

Here is the relevant traceback
```python traceback
fractal_tasks_core/tasks/napari_workflows_wrapper.py:562: in napari_workflows_wrapper
    mask[mask > 0] += max_label_for_relabeling
venv/lib/python3.10/site-packages/stackview/_static_view.py:52: in __getitem__
    return self.obj.__getitem__(index)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = StackViewNDArray([[0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ...,..., 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0],
                  [0, 0, 0, ..., 0, 0, 0]], dtype=int32)
index = <[IndexError('too many indices for array: array is 2-dimensional, but 3 were indexed') raised in repr()] StackViewNDArray object at 0x7509c4a09e40>

    def __getitem__(self, index):
>       return self.obj.__getitem__(index)
E       IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

venv/lib/python3.10/site-packages/stackview/_static_view.py:52: IndexError
```

Note that in
```
mask[mask > 0] += max_label_for_relabeling
```
the variable `max_label_for_relabeling` is an integer, not an array.

**Comment by haesleinhuepf** [comment]
Hi @tcompa ,

thanks again for checking! In order to reproduce the new issue, I might need more details. I tested this minimal-working-example code (with stackvie 0.9.1) and it runs with no error:

```
import numpy as np
from stackview._static_view import StackViewNDArray

labels = StackViewNDArray(np.asarray([
    [0, 1],
    [2,0 ]
]))

labels[labels > 0] += 1
```

Can you modify it and cause the error you observe?

Thanks again!

**Comment by tcompa** [comment]
> Can you modify it and cause the error you observe?

Sure:
```python
import numpy as np
from stackview._static_view import StackViewNDArray

labels = StackViewNDArray(np.asarray([
    [0, 1],
    [2, 0]
]))

labels = np.expand_dims(labels, axis=0)
print(labels)
```

I don't know whether calling `expand_dims` on a `StackViewNDArray` is meant to be supported, but this is the lowest-level Fractal operation that then triggers the error.

**Comment by tcompa** [comment]
A similar example leading to the same error is
```python
import numpy as np
from stackview._static_view import StackViewNDArray

labels = StackViewNDArray(np.asarray([[0, 1], [2, 0]]))
new_labels = labels.reshape((1, 2, 2))
print(new_labels)
```

**Comment by jo-mueller** [comment]
Chiming in: Could the underlying problem be that StackView doesn't know how to handle singleton dimensions? If that's the case, an `array.squeeze()` in the stackview functionality (for instance [here](https://github.com/haesleinhuepf/stackview/blob/4c1e16a0703c70e2c420d22aae42b985e561ecd5/stackview/_image_widget.py#L33)) should possibly do the trick? On the other hand, that would probably limit the ability of the stackview array to cope with singleton dimensions in general🤔

**Comment by haesleinhuepf** [comment]
> If that's the case, an `array.squeeze()` in the stackview functionality (for instance [here](https://github.com/haesleinhuepf/stackview/blob/4c1e16a0703c70e2c420d22aae42b985e561ecd5/stackview/_image_widget.py#L33)) should possibly do the trick?

Great idea! This could help indeed @jo-mueller , just the point the code is definitely wrong. The `StackViewNDArray` is no widget and also doesn't use any widget-related code.

**Comment by haesleinhuepf** [comment]
Ok, one more attempt. I am now overloading all members of the `StackViewNDArray` by forwarding calls to the inner numpy array ([details](https://github.com/haesleinhuepf/stackview/pull/70/files#diff-3207670c74f167ded90792fc77a726005c3c6a7be67775b74d764f5e37e96a26L51-R54)).

@tcompa would you mind trying again with stackview 0.9.2 ? It's on [pypi already](https://pypi.org/project/stackview/0.9.2/) and conda will follow in 12-24h.

**Comment by tcompa** [comment]
> @tcompa would you mind trying again with stackview 0.9.2 ? It's on [pypi already](https://pypi.org/project/stackview/0.9.2/) and conda will follow in 12-24h

When using 0.9.2 I cannot spot any other glitch when running the napari-workflows-related tests of fractal-tasks-core.

**Comment by haesleinhuepf** [comment]
Fantastic, big thanks again for reporting the issue and for testing!

**Comment by haesleinhuepf** [comment]
Fantastic, big thanks again for reporting the issue and for testing!
